apiVersion: v1
baseDomain: $CLUSTER_BASE_DOMAIN
metadata:
  name: $CLUSTER_NAME
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: $MACHINE_NETWORK_CIDR
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIPs:
    - $CLUSTER_API_VIP
    ingressVIPs:
    - $CLUSTER_INGRESS_VIP
pullSecret: '$PULL_SECRET'
sshKey: '$SSH_KEY'